# Service configuration
# You can configure the service exposure here
# be-serviceName for BackEnd, bff-serviceName for BackendForFrontend, dal-serviceName for Data Abstraction Layer
apiVersion: v1
kind: Service
metadata:
  # Normal service name
  name: ms-pta-procces-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    # 8080 normal service, 8081 service with endpoints
    targetPort: 8080
  selector:
    # Normal service name and tier
    app: ms-pta-procces
    # backend, frontend
    tier: backend
  # LOCAL/INTERNAL: NodePort, GCP/EXTERNAL: LoadBalancer
  type: NodePort
